-   name: 'Install aptitude using apt'
    ansible.builtin.apt:
        name: 'aptitude'
        state: 'latest'
        update_cache: true
        force_apt_get: true

-   name: 'Install required system packages'
    ansible.builtin.apt:
        name: '{{ item }}'
        state: 'latest'
        update_cache: true
    loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

-   name: 'Add docker GPG apt key'
    ansible.builtin.apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: 'present'

-   name: 'Add docker repository'
    ansible.builtin.apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
        state: 'present'

-   name: 'Update apt and install docker-ce'
    ansible.builtin.apt:
        update_cache: true
        name: 'docker-ce'
        state: 'latest'

-   name: 'Install docker module for Python'
    ansible.builtin.pip:
        name: 'docker'

-   name: 'Install docker-compose'
    ansible.builtin.pip:
        name: 'docker-compose'
